name: Webhook Broker Integration Test

on:
  push:
    branches: [ 0.1-maint ]
  pull_request:
    branches: [ 0.1-maint ]

jobs:

  integration-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@v1
    - run: make itest
